object Versions {
    const val SLF4J = "2.0.6"
    const val KOTLINX = "1.6.4"
    const val KOTLINX_SERIALIZATION_JSON = "1.4.1"
    const val KOTLIN_LOGGING = "3.0.5"
    const val SUPABASE = "0.8.0-alpha-1"
    const val KTOR = "2.2.3"
    const val KOTEST = "5.5.4"
    const val CLIKT = "3.5.2"
}

plugins {
    kotlin("jvm") version "1.8.10"
    id("edu.sc.seis.launch4j") version "2.5.4"
    id ("com.github.breadmoirai.github-release") version "2.4.1"
    application
}


group = "app.hsc"
version = "0.13"

repositories {
    mavenCentral()
    mavenLocal()
    maven("https://jitpack.io")
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:${Versions.CLIKT}")
    implementation("io.kotest:kotest-assertions-core:${Versions.KOTEST}")
    implementation("io.kotest:kotest-framework-engine:${Versions.KOTEST}")
    implementation("io.kotest:kotest-property:${Versions.KOTEST}")
    implementation(kotlin("test-common"))
    implementation(kotlin("test-annotations-common"))
    implementation("io.github.jan-tennert.supabase:postgrest-kt:${Versions.SUPABASE}")
    implementation("io.github.jan-tennert.supabase:gotrue-kt:${Versions.SUPABASE}")
    implementation("io.github.jan-tennert.supabase:functions-kt:${Versions.SUPABASE}")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.KOTLINX_SERIALIZATION_JSON}")
    implementation("io.ktor:ktor-client-core:${Versions.KTOR}")
    implementation("io.ktor:ktor-client-cio:${Versions.KTOR}")
    implementation("io.ktor:ktor-client-apache:${Versions.KTOR}")
    implementation("io.github.microutils:kotlin-logging:${Versions.KOTLIN_LOGGING}")
    implementation("org.slf4j:slf4j-simple:${Versions.SLF4J}")
    testImplementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0")
    implementation("com.github.vishna:watchservice-ktx:master-SNAPSHOT")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.KOTLINX}")
    implementation("io.github.java-diff-utils:java-diff-utils:4.12")
    implementation("org.awaitility:awaitility:4.2.0")
    implementation("net.java.dev.jna:jna:5.13.0")
    implementation("net.java.dev.jna:jna-platform:5.13.0")
    testImplementation(kotlin("test"))
}

tasks.jar {
    manifest.attributes["Main-Class"] = "app.hsc.Main"
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .map(::zipTree)
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType<Test> {
    useJUnitPlatform()
    filter {
        isFailOnNoMatchingTests = false
    }
    testLogging {
        showExceptions = true
        showStandardStreams = true
        events = setOf(
            org.gradle.api.tasks.testing.logging.TestLogEvent.FAILED,
            org.gradle.api.tasks.testing.logging.TestLogEvent.PASSED
        )
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}

launch4j {
    mainClassName = "app.hsc.Main"
}

githubRelease {
    token(System.getenv("GITHUB_TOKEN")) // This is your personal access token with Repo permissions
    // You get this from your user settings > developer settings > Personal Access Tokens
    owner("huntcomp") // default is the last part of your group. Eg group: "com.github.breadmoirai" => owner: "breadmoirai"
    repo("hsc-daemon") // by default this is set to your project name
    tagName( "v0.13") // by default this is set to "v${project.version}"
    targetCommitish ("main") // by default this is set to "main"
    releaseName ("v0.13")// Release title, by default this is the same as the tagName
    generateReleaseNotes(false) // Generate release notes automatically, if true and body is present, body will be prepended, if name is not given, one will be generated by the tag // by default this is empty
    prerelease(true)
    body(provider(changelog()))
    releaseAssets( "build/launch4j/hsc-daemon.exe" ) // this points to which files you want to upload as assets with your release, by default this is empty
    overwrite(true) // by default false; if set to true, will delete an existing release with the same tag and name
    dryRun(false)// by default false; you can use this to see what actions would be taken without making a release
}

kotlin {
    jvmToolchain(11)

    application {
        mainClass.set("hsc.app.Main")
    }

}
buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
    }
}
